import Head from 'next/head'



import Navbar from '@/components/Navbar'
import Screen from '../components/Screen';



export default function Home() {
  return (
    <>
      <Head>
        <title>Placebook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://cdn2.iconfinder.com/data/icons/letters-and-numbers-1/32/lowercase_letter_p_red-512.png" />
      </Head>
      <header>
         <Navbar/>
      </header>
      <main className="">  
         <Screen/>
      </main>
      <footer>
         
      </footer>
    </>
  )
}
